export const metadata = {
  title: 'Terms of Service — UUIDWalls',
  description: 'Terms of Service for UUIDWalls by KJR Labs.',
}

export default function TermsPage() {
  return (
    <main style={{ background: 'var(--ink)', minHeight: '100vh', padding: '4rem 2rem' }}>
      <div style={{ maxWidth: '680px', margin: '0 auto' }}>

        <a href="/" style={{ fontFamily: 'var(--mono)', fontSize: '11px', color: 'var(--p30)', textDecoration: 'none', letterSpacing: '0.06em', display: 'inline-block', marginBottom: '3rem' }}>
          &larr; uuidwalls.vercel.app
        </a>

        <h1 style={{ fontFamily: 'var(--serif)', fontSize: 'clamp(2rem, 5vw, 3rem)', fontWeight: 700, color: 'var(--paper)', letterSpacing: '-0.02em', marginBottom: '0.5rem' }}>
          Terms of Service
        </h1>
        <p style={{ fontFamily: 'var(--mono)', fontSize: '10px', color: 'var(--p30)', letterSpacing: '0.06em', marginBottom: '3rem' }}>
          Last updated: April 2026
        </p>

        <div style={{ fontFamily: 'var(--sans)', fontSize: '0.9rem', color: 'var(--p55)', lineHeight: '1.8', display: 'flex', flexDirection: 'column', gap: '2rem' }}>

          <section>
            <h2 style={{ fontFamily: 'var(--serif)', fontSize: '1.3rem', fontWeight: 700, color: 'var(--paper)', marginBottom: '0.75rem' }}>1. Acceptance</h2>
            <p>By accessing or using UUIDWalls (&ldquo;the Service&rdquo;), you agree to be bound by these Terms of Service. If you do not agree, please do not use the Service. The Service is operated by KJR Labs (Kshitij Koranne), an independent software builder based in India.</p>
          </section>

          <section>
            <h2 style={{ fontFamily: 'var(--serif)', fontSize: '1.3rem', fontWeight: 700, color: 'var(--paper)', marginBottom: '0.75rem' }}>2. Description of Service</h2>
            <p>UUIDWalls is a generative wallpaper web application that converts a device UUID into a deterministic, unique wallpaper across six pattern families. The Service offers free screen-resolution downloads and a one-time paid unlock for 2K (2560&times;1440) and 4K (3840&times;2160) resolution downloads.</p>
          </section>

          <section>
            <h2 style={{ fontFamily: 'var(--serif)', fontSize: '1.3rem', fontWeight: 700, color: 'var(--paper)', marginBottom: '0.75rem' }}>3. Accounts</h2>
            <p>Certain features, including high-resolution downloads, require you to create an account via Google OAuth or a magic link email. You are responsible for maintaining the confidentiality of your account. We reserve the right to suspend or terminate accounts that violate these terms.</p>
          </section>

          <section>
            <h2 style={{ fontFamily: 'var(--serif)', fontSize: '1.3rem', fontWeight: 700, color: 'var(--paper)', marginBottom: '0.75rem' }}>4. Payments</h2>
            <p>The 2K/4K unlock is available for a one-time payment of ₹99 (Indian Rupees), processed securely via Razorpay. Payment is charged at the time of purchase. All prices are inclusive of applicable taxes where required. Once the purchase is confirmed, the unlock is applied to your account permanently and is non-transferable.</p>
          </section>

          <section>
            <h2 style={{ fontFamily: 'var(--serif)', fontSize: '1.3rem', fontWeight: 700, color: 'var(--paper)', marginBottom: '0.75rem' }}>5. Refunds</h2>
            <p>All purchases are final and non-refundable. Because the 2K/4K download unlock is a digital product delivered instantly upon payment confirmation, we do not offer refunds under any circumstances. Please refer to our <a href="/refund" style={{ color: 'var(--p85)', textDecoration: 'none' }}>Refund Policy</a> for full details.</p>
          </section>

          <section>
            <h2 style={{ fontFamily: 'var(--serif)', fontSize: '1.3rem', fontWeight: 700, color: 'var(--paper)', marginBottom: '0.75rem' }}>6. Intellectual Property</h2>
            <p style={{ marginBottom: '0.75rem' }}>The wallpapers generated by UUIDWalls are produced deterministically from your input UUID using our rendering engine. You are granted a personal, non-exclusive licence to use the wallpapers you generate for personal, non-commercial purposes.</p>
            <p>The UUIDWalls name, logo, design system, codebase, and all underlying software are the intellectual property of KJR Labs and may not be copied, reproduced, or redistributed without written permission.</p>
          </section>

          <section>
            <h2 style={{ fontFamily: 'var(--serif)', fontSize: '1.3rem', fontWeight: 700, color: 'var(--paper)', marginBottom: '0.75rem' }}>7. Acceptable Use</h2>
            <p style={{ marginBottom: '0.75rem' }}>You agree not to:</p>
            <ul style={{ paddingLeft: '1.25rem', display: 'flex', flexDirection: 'column', gap: '0.4rem' }}>
              <li>Attempt to circumvent, reverse-engineer, or bypass the payment or download gating mechanisms.</li>
              <li>Use automated scripts or bots to access the Service in a manner that places unreasonable load on our infrastructure.</li>
              <li>Resell or commercially redistribute wallpapers generated by the Service without our express written consent.</li>
              <li>Use the Service in violation of any applicable laws or regulations.</li>
            </ul>
          </section>

          <section>
            <h2 style={{ fontFamily: 'var(--serif)', fontSize: '1.3rem', fontWeight: 700, color: 'var(--paper)', marginBottom: '0.75rem' }}>8. Disclaimer of Warranties</h2>
            <p>The Service is provided &ldquo;as is&rdquo; and &ldquo;as available&rdquo; without warranties of any kind, express or implied. We do not warrant that the Service will be uninterrupted, error-free, or that any defects will be corrected. Your use of the Service is at your sole risk.</p>
          </section>

          <section>
            <h2 style={{ fontFamily: 'var(--serif)', fontSize: '1.3rem', fontWeight: 700, color: 'var(--paper)', marginBottom: '0.75rem' }}>9. Limitation of Liability</h2>
            <p>To the fullest extent permitted by applicable law, KJR Labs shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising from your use of or inability to use the Service. Our total liability to you for any claim shall not exceed the amount you paid us in the twelve months preceding the claim.</p>
          </section>

          <section>
            <h2 style={{ fontFamily: 'var(--serif)', fontSize: '1.3rem', fontWeight: 700, color: 'var(--paper)', marginBottom: '0.75rem' }}>10. Governing Law</h2>
            <p>These Terms are governed by the laws of India. Any disputes shall be subject to the exclusive jurisdiction of the courts located in Vadodara, Gujarat, India.</p>
          </section>

          <section>
            <h2 style={{ fontFamily: 'var(--serif)', fontSize: '1.3rem', fontWeight: 700, color: 'var(--paper)', marginBottom: '0.75rem' }}>11. Changes to These Terms</h2>
            <p>We reserve the right to modify these Terms at any time. The &ldquo;Last updated&rdquo; date reflects the most recent revision. Continued use of the Service after changes are posted constitutes your acceptance of the revised Terms.</p>
          </section>

          <section>
            <h2 style={{ fontFamily: 'var(--serif)', fontSize: '1.3rem', fontWeight: 700, color: 'var(--paper)', marginBottom: '0.75rem' }}>12. Contact</h2>
            <p>For any questions regarding these Terms, contact us at <a href="mailto:kjrlabs9@gmail.com" style={{ color: 'var(--p85)', textDecoration: 'none' }}>kjrlabs9@gmail.com</a>.</p>
          </section>

        </div>

        <div style={{ display: 'flex', gap: '1.5rem', marginTop: '4rem', paddingTop: '2rem', borderTop: '1px solid var(--p08)', flexWrap: 'wrap' }}>
          <a href="/privacy" style={{ fontFamily: 'var(--mono)', fontSize: '10px', color: 'var(--p30)', textDecoration: 'none', letterSpacing: '0.06em' }}>Privacy Policy</a>
          <a href="/refund" style={{ fontFamily: 'var(--mono)', fontSize: '10px', color: 'var(--p30)', textDecoration: 'none', letterSpacing: '0.06em' }}>Refund Policy</a>
          <a href="/" style={{ fontFamily: 'var(--mono)', fontSize: '10px', color: 'var(--p30)', textDecoration: 'none', letterSpacing: '0.06em' }}>Home</a>
        </div>

      </div>
    </main>
  )
}
